In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('transactions.csv')
df

,transaction_id,user_id,timestamp,amount,country,device,channel,hour,dayofweek,coupon_applied,num_items,is_fraud
0,6253,3594,28-01-2023 06:04,125.79,US,mobile,ads,6,5,0,5,0
1,4685,2502,27-04-2023 21:32,153.40,DE,mobile,web,21,3,0,3,0
2,1732,2287,19-08-2023 19:03,7.64,IN,tablet,app,19,5,0,3,0
3,4743,3043,14-03-2023 04:56,36.36,US,mobile,web,4,1,1,2,0
4,4522,4629,24-09-2023 21:33,55.17,ES,mobile,app,21,6,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,5735,1520,21-02-2023 06:20,10.74,ES,tablet,web,6,1,1,1,0
9996,5192,1648,02-09-2023 12:51,76.97,BR,mobile,ads,12,5,0,2,0
9997,5391,2776,18-01-2023 13:41,56.48,AU,mobile,email,13,2,0,4,0
9998,861,2856,15-04-2023 15:25,6.64,US,mobile,web,15,5,1,3,0
9999,7271,1795,18-10-2023 09:18,139.81,ES,desktop,web,9,2,0,2,0

In [3]:
req = ['transaction_id', 'user_id', 'amount', 'country', 'timestamp', 'is_fraud']
df = df[req]

In [4]:
df.head()

   transaction_id  user_id  amount country         timestamp  is_fraud
0            6253     3594  125.79      US  28-01-2023 06:04         0
1            4685     2502  153.40      DE  27-04-2023 21:32         0
2            1732     2287    7.64      IN  19-08-2023 19:03         0
3            4743     3043   36.36      US  14-03-2023 04:56         0
4            4522     4629   55.17      ES  24-09-2023 21:33         0

In [5]:
df.to_csv('cleaned.csv', index=False)